name = "Barrel"
version = "0.1.0"
defaultTargets = ["Barrel"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.25.0"

[[lean_lib]]
name = "Barrel"

[[lean_lib]]
name = "Extra"

[[lean_lib]]
name = "B"

[[lean_lib]]
name = "POGReader"
